# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94cdac3ea2155c3ccd021ef6095cb307cd88b2cf5f885dd3be4b7c48ec488cd0fc31a248c86dc19127709cc30a6449ef597cfbf045cece482a73574b956bf8a4

test:
  secret_key_base: 026b9764bc9e1bc3e4668ab70c19b4924455c87fac9a88e96a89aa44b832392b4104b300749df393364e80bf92c0282dbe4d56e39c2e44844a4eda836bb86fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
